/* destinos (id_destino, nombre) */

INSERT INTO DESTINOS VALUES (1,'Canal de Panama');
INSERT INTO DESTINOS VALUES (2,'Biomuseo');
INSERT INTO DESTINOS VALUES (3,'Casco Antiguo');
INSERT INTO DESTINOS VALUES (4,'Panama Viejo');
INSERT INTO DESTINOS VALUES (5,'Portobelo');
INSERT INTO DESTINOS VALUES (6,'San Blas');
INSERT INTO DESTINOS VALUES (7,'Isla Grande');
INSERT INTO DESTINOS VALUES (8,'Valle de anton');
INSERT INTO DESTINOS VALUES (9,'Cerro azul');
INSERT INTO DESTINOS VALUES (10,'Volcan baru');
INSERT INTO DESTINOS VALUES (11,'Archipielago de las perlas');
INSERT INTO DESTINOS VALUES (12,'Boquete');
INSERT INTO DESTINOS VALUES (13,'Cerro ancon');
INSERT INTO DESTINOS VALUES (14,'Punta chame');
INSERT INTO DESTINOS VALUES (15,'Calzada amador');
INSERT INTO DESTINOS VALUES (16,'Bocas del Toro');