/* DESTINOS_TOURS (id_tour, id_destino, */
INSERT INTO BOOKING VALUES(1,1);
INSERT INTO BOOKING VALUES(1,2);
INSERT INTO BOOKING VALUES(1,3);
INSERT INTO BOOKING VALUES(1,4);
INSERT INTO BOOKING VALUES(1,15);
INSERT INTO BOOKING VALUES(2,3);
INSERT INTO BOOKING VALUES(3,6);
INSERT INTO BOOKING VALUES(4,7);
INSERT INTO BOOKING VALUES(4,5);
INSERT INTO BOOKING VALUES(5,8);
INSERT INTO BOOKING VALUES(6,10);
INSERT INTO BOOKING VALUES(7,10);
INSERT INTO BOOKING VALUES(8,16);
INSERT INTO BOOKING VALUES(9,16);
INSERT INTO BOOKING VALUES(10,12);

