/* DESTINOS_TOURS (id_tour, id_destino, */
INSERT INTO DESTINOS_TOURS VALUES(1,1);
INSERT INTO DESTINOS_TOURS VALUES(1,2);
INSERT INTO DESTINOS_TOURS VALUES(1,3);
INSERT INTO DESTINOS_TOURS VALUES(1,4);
INSERT INTO DESTINOS_TOURS VALUES(1,15);
INSERT INTO DESTINOS_TOURS VALUES(2,3);
INSERT INTO DESTINOS_TOURS VALUES(3,6);
INSERT INTO DESTINOS_TOURS VALUES(4,7);
INSERT INTO DESTINOS_TOURS VALUES(4,5);
INSERT INTO DESTINOS_TOURS VALUES(5,8);
INSERT INTO DESTINOS_TOURS VALUES(6,10);
INSERT INTO DESTINOS_TOURS VALUES(7,10);
INSERT INTO DESTINOS_TOURS VALUES(8,16);
INSERT INTO DESTINOS_TOURS VALUES(9,16);
INSERT INTO DESTINOS_TOURS VALUES(10,12);

