/* DESTINOS_TOURS (id_destino, id_tour, */
INSERT INTO DESTINOS_TOURS VALUES (1, 1);
INSERT INTO DESTINOS_TOURS VALUES (2, 1);
INSERT INTO DESTINOS_TOURS VALUES (3, 1);
INSERT INTO DESTINOS_TOURS VALUES (4, 1);
INSERT INTO DESTINOS_TOURS VALUES (15, 1);
INSERT INTO DESTINOS_TOURS VALUES (3, 2);
INSERT INTO DESTINOS_TOURS VALUES (4, 2);
INSERT INTO DESTINOS_TOURS VALUES (6, 3);
INSERT INTO DESTINOS_TOURS VALUES (5, 4);
INSERT INTO DESTINOS_TOURS VALUES (7, 4);
INSERT INTO DESTINOS_TOURS VALUES (8, 5);
INSERT INTO DESTINOS_TOURS VALUES (10, 6);
INSERT INTO DESTINOS_TOURS VALUES (10, 7);
INSERT INTO DESTINOS_TOURS VALUES (16, 8);
INSERT INTO DESTINOS_TOURS VALUES (16, 9);
INSERT INTO DESTINOS_TOURS VALUES (11, 10);



