/* booking_tours (ID_bookingtour, tour_id)*/

INSERT INTO BOOKING VALUES(1,1);
INSERT INTO BOOKING VALUES(1,2);
INSERT INTO BOOKING VALUES(2,7);
INSERT INTO BOOKING VALUES(4,9);
INSERT INTO BOOKING VALUES(5,16);
INSERT INTO BOOKING VALUES(6,11);
INSERT INTO BOOKING VALUES(7,13);
INSERT INTO BOOKING VALUES(8,15);
INSERT INTO BOOKING VALUES(9,9);
INSERT INTO BOOKING VALUES(10,7);