/* CREACION DE USUARIOS */

GRANT CREATE SESSION TO miusuario;

CREATE USER usuario IDENTIFIED BY contrasena;

/* CREACION DE USUARIOS */
CREATE USER usuario IDENTIFIED BY contrasena;
/*CONCEDER PERMISOS*/
GRANT CONNECT TO usuario;
GRANT RESOURCE TO usuario;
GRANT CREATE VIEW TO usuario; 